version: "3"
services:
  db:
    container_name: db
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=#TFGD3J0s3b4#
      - POSTGRES_DB=nmap
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
      - ./db/inicializar.sql:/docker-entrypoint-initdb.d/inicializar.sql
  web:
    container_name: web
    build: ./app/
    ports:
      - "443:443"
    links:
      - db
    volumes:
      - ./app/:/var/www/html/
      - ./certs:/etc/ssl/certs
      - ./certs:/etc/ssl/private
    environment:
      - ALLOW_OVERRIDE=true
      - APACHE_SSL_CERT_FILE=/etc/ssl/certs/server.crt
      - APACHE_SSL_KEY_FILE=/etc/ssl/private/server.key

  app:
    container_name: app
    build: .
    volumes:
      - ./:/usr/src/app
    depends_on:
      - db
      
volumes:
  db:
